# CAMINHO DO ARQUIVO DE CONFIGURAÇÃO DAS PROPRIEDADES
CAMINHO_ARQUIVO_CONFIG = 'gameConfig.txt'

# RODADAS MÁXIMAS PERMITIDAS
ROADAS_MAXIMAS = 10

# CONSTANTES DE COMPORTAMENTO
COMPORTAMENTO_1 = 'impulsivo'
COMPORTAMENTO_2 = 'exigente'
COMPORTAMENTO_3 = 'cauteloso'
COMPORTAMENTO_4 = 'aleatório'

